# Generated by Django 5.2.5 on 2025-08-30 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("material", "0001_initial"),
        ("production", "0002_initial"),
        ("workcenter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="work_center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="workcenter.workcenter",
            ),
        ),
        migrations.AddField(
            model_name="usedmaterial",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="material.material"
            ),
        ),
        migrations.AddField(
            model_name="usedmaterial",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="used_materials",
                to="production.order",
            ),
        ),
    ]
