# Generated by Django 5.2.5 on 2025-09-01 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_product_price"),
        ("production", "0003_initial"),
        ("workcenter", "0002_alter_workcenter_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("EXTRUSION", "Extrusion"),
                            ("DEGASSING", "Degassing (10 kun)"),
                            ("LAMINATION", "Lamination"),
                            ("BRONZING", "Bronzing"),
                            ("DUPLICATION", "Duplication"),
                            ("PACKAGING", "Packaging"),
                            ("QUALITY_CONTROL", "Quality Control"),
                            ("WAREHOUSE_TRANSFER", "Warehouse Transfer"),
                            ("CUSTOMER_DELIVERY", "Customer Delivery"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Step duration in hours",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                (
                    "order_sequence",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of execution"
                    ),
                ),
            ],
            options={
                "ordering": ["order_sequence"],
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="produced_material",
        ),
        migrations.RemoveField(
            model_name="order",
            name="work_center",
        ),
        migrations.AddField(
            model_name="order",
            name="completion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="produced_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produced_by",
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="unit_of_measure",
            field=models.CharField(
                choices=[
                    ("KG", "kg"),
                    ("METER", "m"),
                    ("METER_SQUARE", "m²"),
                    ("METER_CUBIC", "m³"),
                    ("PIECE", "piece"),
                    ("LITER", "l"),
                ],
                default="KG",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="produced_quantity",
            field=models.DecimalField(
                decimal_places=2, help_text="Production quantity", max_digits=10
            ),
        ),
        migrations.CreateModel(
            name="ProductionStepExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("SKIPPED", "Skipped"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "actual_duration_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "quality_notes",
                    models.TextField(
                        blank=True, help_text="Quality control notes", null=True
                    ),
                ),
                (
                    "quantity_processed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "assigned_operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_executions",
                        to="production.order",
                    ),
                ),
                (
                    "production_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.productionstep",
                    ),
                ),
                (
                    "work_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workcenter.workcenter",
                    ),
                ),
            ],
            options={
                "ordering": ["production_step__order_sequence"],
                "unique_together": {("order", "production_step")},
            },
        ),
        migrations.CreateModel(
            name="ProductionOutput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "step_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="production.productionstepexecution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="usedmaterial",
            name="step_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials_used",
                to="production.productionstepexecution",
            ),
        ),
    ]
