# Generated by Django 5.2.5 on 2025-09-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0004_productionstep_remove_order_produced_material_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionoutput",
            name="unit_of_measure",
            field=models.CharField(
                choices=[
                    ("KG", "kg"),
                    ("METER", "m"),
                    ("METER_SQUARE", "m²"),
                    ("METER_CUBIC", "m³"),
                    ("PIECE", "piece"),
                    ("LITER", "l"),
                ],
                default="KG",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="productionoutput",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="og'irlik",
                max_digits=10,
                null=True,
            ),
        ),
    ]
