# Generated by Django 5.2.5 on 2025-08-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_productcomponent"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
