# Generated by Django 5.2.5 on 2025-08-30 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("material", "0001_initial"),
        ("stock", "0001_initial"),
        ("warehouse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymateriallog",
            name="from_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outgoing_inventory_logs",
                to="warehouse.location",
            ),
        ),
        migrations.AddField(
            model_name="inventorymateriallog",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_material_logs",
                to="material.material",
            ),
        ),
        migrations.AddField(
            model_name="inventorymateriallog",
            name="to_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incoming_inventory_logs",
                to="warehouse.location",
            ),
        ),
        migrations.AddField(
            model_name="inventorymateriallog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stocklevel",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="warehouse.location"
            ),
        ),
        migrations.AddField(
            model_name="stocklevel",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="material.material"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorymateriallog",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)),
                name="inventorylog_quantity_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorymateriallog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("from_location__isnull", True),
                    ("to_location__isnull", True),
                    _negated=True,
                ),
                name="inventorylog_from_or_to_present",
            ),
        ),
        migrations.AddIndex(
            model_name="stocklevel",
            index=models.Index(fields=["material", "location"], name="ix_stk_mat_loc"),
        ),
        migrations.AddConstraint(
            model_name="stocklevel",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gte", 0)),
                name="stocklevel_quantity_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklevel",
            constraint=models.UniqueConstraint(
                fields=("material", "location"), name="uq_stocklevel_material_location"
            ),
        ),
    ]
