# Generated by Django 5.2.5 on 2025-08-30 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0003_rename_inventorymateriallog_inventorymovementlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorymovementlog",
            name="timestamp",
        ),
    ]
