# Generated by Django 5.0.1 on 2025-08-31 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0002_material_price"),
        ("product", "0003_product_price"),
        ("stock", "0004_remove_inventorymovementlog_timestamp"),
        ("warehouse", "0004_remove_location_location_type_matches_reference_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymovementlog",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_product_logs",
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="stocklevel",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="stocklevel",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="material.material",
            ),
        ),
        migrations.AddIndex(
            model_name="stocklevel",
            index=models.Index(fields=["product", "location"], name="ix_stk_prod_loc"),
        ),
        migrations.AddConstraint(
            model_name="inventorymovementlog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("material__isnull", True), ("product__isnull", True), _negated=True
                ),
                name="inventorylog_material_or_product_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorymovementlog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("material__isnull", False),
                    ("product__isnull", False),
                    _negated=True,
                ),
                name="inventorylog_material_or_product_not_both",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklevel",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("material__isnull", True), ("product__isnull", True), _negated=True
                ),
                name="stocklevel_material_or_product_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklevel",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("material__isnull", False),
                    ("product__isnull", False),
                    _negated=True,
                ),
                name="stocklevel_material_or_product_not_both",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklevel",
            constraint=models.UniqueConstraint(
                fields=("product", "location"), name="uq_stocklevel_product_location"
            ),
        ),
    ]
