# Generated by Django 5.2.5 on 2025-08-30 12:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("KG", "kg"),
                            ("METER", "m"),
                            ("METER_SQUARE", "m²"),
                            ("METER_CUBIC", "m³"),
                            ("PIECE", "piece"),
                            ("LITER", "l"),
                        ],
                        default="KG",
                        max_length=12,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("GRANULA", "Granula"),
                            ("ZAR", "Zar"),
                            ("OTHER", "Other"),
                        ],
                        default="GRANULA",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
