# Generated by Django 5.0.1 on 2025-09-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADMIN", "Admin"),
                    ("DIRECTOR", "Director"),
                    ("HISOBCHI", "Hisobchi"),
                    ("TEXNOLOG", "Texnolog"),
                    ("WAREHOUSE", "Warehouse"),
                    ("SMENA_BOSHLIGI", "Smena Boshlig'i"),
                    ("KATTA_MUTAXASSIS", "Katta Mutaxassis"),
                    ("KICHIK_MUTAXASSIS", "Kichik Mutaxassis"),
                    ("STAJER", "Stajer"),
                    ("WORKER", "Worker"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
