# Generated by Django 5.2.5 on 2025-08-30 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("warehouse", "0001_initial"),
        ("workcenter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="work_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="workcenter.workcenter",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="warehouse.warehouse",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("location_type", "WAREHOUSE"),
                        ("warehouse__isnull", False),
                        ("work_center__isnull", True),
                    ),
                    models.Q(
                        ("location_type", "WORKCENTER"),
                        ("warehouse__isnull", True),
                        ("work_center__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="location_type_matches_reference",
            ),
        ),
    ]
