# Generated by Django 5.2.5 on 2025-08-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("WAREHOUSE", "Warehouse"),
                    ("WORKCENTER", "Work Center Staging"),
                    ("WORKSHOP", "Workshop"),
                ],
                max_length=20,
            ),
        ),
    ]
