# Generated by Django 5.2.5 on 2025-08-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0003_alter_location_location_type"),
        ("workcenter", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="location",
            name="location_type_matches_reference",
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("location_type", "WAREHOUSE"),
                        ("warehouse__isnull", False),
                        ("work_center__isnull", True),
                    ),
                    models.Q(
                        ("location_type", "WORKCENTER"),
                        ("warehouse__isnull", True),
                        ("work_center__isnull", False),
                    ),
                    models.Q(
                        ("location_type", "WORKSHOP"),
                        ("warehouse__isnull", True),
                        ("work_center__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="location_type_matches_reference",
            ),
        ),
    ]
