# Generated by Django 5.2.5 on 2025-08-30 12:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkCenter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXTRUDER", "Extruder"),
                            ("DUPLICATOR", "Duplicator"),
                            ("LAMINATOR", "Laminator"),
                            ("BRONIROVSHIK", "Bronirovshik"),
                            ("BRAK MAYDALAGICH", "Brak maydalagich"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("capacity_per_hour", models.IntegerField(blank=True, null=True)),
                (
                    "capacity_unit",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.location",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
