# Generated by Django 5.2.5 on 2025-09-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workcenter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workcenter",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXTRUDER", "Extruder"),
                    ("DEGASSING_AREA", "Degassing Area"),
                    ("LAMINATOR", "Laminator"),
                    ("BRONIROVSHIK", "Bronirovshik"),
                    ("DUPLICATOR", "Duplicator"),
                    ("PACKAGING", "Packaging"),
                    ("QUALITY_CONTROL", "Quality Control"),
                    ("BRAK_MAYDALAGICH", "Brak maydalagich"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
